version: "2.21"

services:
  database:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes: 
      - .:/usr/apps
      
volumes:
  pgdata:
    driver: local